-- Velo Nero Supabase schema. Apply from Supabase SQL editor or supabase db push.
create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('none','member','vice','boss','owner','admin');
exception when duplicate_object then null; end $$;

create table if not exists public.roles (
  name text primary key,
  rank int not null default 0,
  label text not null
);

insert into public.roles (name, rank, label) values
  ('none',0,'Nessun ruolo'),('member',1,'Member'),('vice',2,'Vice'),('boss',3,'Boss'),('owner',4,'Owner'),('admin',5,'Admin')
on conflict (name) do update set rank = excluded.rank, label = excluded.label;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email text not null unique,
  username text not null default '',
  name text not null default '',
  picture text not null default '',
  role text not null default 'none' references public.roles(name),
  blocked boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists profiles_role_idx on public.profiles(role);

create table if not exists public.auth_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  email text not null,
  token_type text not null default 'cookie',
  revoked_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  actor_email text,
  actor_role text,
  target_email text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists activity_logs_created_idx on public.activity_logs(created_at desc);

create table if not exists public.diary_entries (
  id text primary key,
  at bigint not null,
  day date not null,
  title text not null default '',
  text text not null,
  by_email text not null,
  by_role text not null default 'none',
  created_at timestamptz not null default now()
);
create index if not exists diary_entries_at_idx on public.diary_entries(at desc);
create index if not exists diary_entries_day_idx on public.diary_entries(day, at desc);

create table if not exists public.actions (
  id text primary key,
  at bigint not null,
  amount numeric not null,
  notes text not null default '',
  by_email text not null,
  by_role text not null default 'none',
  created_at timestamptz not null default now()
);
create index if not exists actions_at_idx on public.actions(at desc);

create table if not exists public.traffic_records (
  id text primary key,
  at bigint not null,
  area text not null check (area in ('armi','droga')),
  type text not null check (type in ('acquisto','vendita','movimento')),
  item text not null,
  qty numeric not null check (qty > 0),
  notes text not null default '',
  by_email text not null,
  by_role text not null default 'none',
  created_at timestamptz not null default now()
);
create index if not exists traffic_records_at_idx on public.traffic_records(at desc);
create index if not exists traffic_records_area_idx on public.traffic_records(area, at desc);

-- Initial admin profile. Create the Auth user in Supabase Auth with this same email and temporary password Mike00.
insert into public.profiles (email, username, name, role)
values ('m.colurci@gmail.com', 'Mike', 'Mike', 'admin')
on conflict (email) do update set username='Mike', name='Mike', role='admin', updated_at=now();

-- Data API permissions for server-side REST calls with SUPABASE_SERVICE_ROLE_KEY.
-- Without explicit grants, PostgREST can return 42501 permission denied on new objects.
grant usage on schema public to service_role;

grant all privileges on table public.roles to service_role;
grant all privileges on table public.profiles to service_role;
grant all privileges on table public.auth_tokens to service_role;
grant all privileges on table public.activity_logs to service_role;
grant all privileges on table public.diary_entries to service_role;
grant all privileges on table public.actions to service_role;
grant all privileges on table public.traffic_records to service_role;

-- Required for inserts into identity/serial-backed tables through the Data API.
-- Grant on all sequences avoids depending on PostgreSQL-generated sequence names.
grant all privileges on all sequences in schema public to service_role;
